# Step1: We are ready to talk to API
# Step2: to target our API: add "games" from Program.cs: app.MapGet("games", () => games);
GET http://localhost:5065/games

###
# Click on "Send request", can see it gets the data from id 1
GET http://localhost:5065/games/4

###
POST http://localhost:5065/games/
Content-Type: application/json
 
{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}
